const PATIENT_BOOKABLE_SERVICES = [
  {
    code: "NGAP-CONSULT-GENERALE",
    name: "Consultation générale",
    description: "Consultation chez un médecin généraliste",
    department: "GENERAL",
    category: "CONSULTATION",
    pricing_type: "DIRECT",
    direct_price: 200,
    coefficient: 1,
    letter: "C",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-CONSULT-SPECIALISTE",
    name: "Consultation spécialiste",
    description: "Consultation chez un médecin spécialiste",
    department: "SPECIALISTE",
    category: "CONSULTATION",
    pricing_type: "DIRECT",
    direct_price: 250,
    coefficient: 1,
    letter: "Cs",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-VISITE-DOMICILE",
    name: "Visite à domicile",
    description: "Visite médicale à domicile",
    department: "GENERAL",
    category: "CONSULTATION",
    pricing_type: "DIRECT",
    direct_price: 300,
    coefficient: 1,
    letter: "V",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-ECG",
    name: "Électrocardiogramme (ECG)",
    description: "Examen de l’activité électrique du cœur",
    department: "CARDIOLOGIE",
    category: "DIAGNOSTIC",
    pricing_type: "DIRECT",
    direct_price: 150,
    coefficient: 10,
    letter: "K",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-EEG",
    name: "Électroencéphalogramme (EEG)",
    description: "Analyse de l’activité cérébrale",
    department: "NEUROLOGIE",
    category: "DIAGNOSTIC",
    pricing_type: "DIRECT",
    direct_price: 300,
    coefficient: 30,
    letter: "D",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-ECHO-ENC",
    name: "Écho-encéphalogramme",
    description: "Imagerie cérébrale par ultrasons",
    department: "NEUROLOGIE",
    category: "IMAGING",
    pricing_type: "DIRECT",
    direct_price: 120,
    coefficient: 10,
    letter: "D",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-RADIO-THORAX",
    name: "Radiographie thoracique",
    description: "Radiographie des poumons",
    department: "RADIOLOGIE",
    category: "IMAGING",
    pricing_type: "DIRECT",
    direct_price: 180,
    coefficient: 15,
    letter: "Z",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-ECHOGRAPHIE",
    name: "Échographie abdominale",
    description: "Exploration par ultrasons de l’abdomen",
    department: "RADIOLOGIE",
    category: "IMAGING",
    pricing_type: "DIRECT",
    direct_price: 350,
    coefficient: 20,
    letter: "KE",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-INJECTION-SC",
    name: "Injection sous-cutanée",
    description: "Injection médicamenteuse sous la peau",
    department: "SOINS",
    category: "INFIRMIER",
    pricing_type: "DIRECT",
    direct_price: 50,
    coefficient: 1,
    letter: "C",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-INJECTION-IM",
    name: "Injection intramusculaire",
    description: "Injection dans le muscle",
    department: "SOINS",
    category: "INFIRMIER",
    pricing_type: "DIRECT",
    direct_price: 60,
    coefficient: 1,
    letter: "C",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-PANSEMENT",
    name: "Pansement simple",
    description: "Soin de plaie superficielle",
    department: "SOINS",
    category: "INFIRMIER",
    pricing_type: "DIRECT",
    direct_price: 70,
    coefficient: 5,
    letter: "C",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-SUTURE-PLAIE",
    name: "Suture de plaie",
    description: "Fermeture d’une plaie",
    department: "CHIRURGIE",
    category: "URGENCE",
    pricing_type: "DIRECT",
    direct_price: 200,
    coefficient: 10,
    letter: "C",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-ABCES-DRAINAGE",
    name: "Drainage d’abcès",
    description: "Incision et drainage d’une collection",
    department: "CHIRURGIE",
    category: "URGENCE",
    pricing_type: "DIRECT",
    direct_price: 250,
    coefficient: 20,
    letter: "C",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-PRISE-SANG",
    name: "Prise de sang",
    description: "Prélèvement sanguin",
    department: "LABORATOIRE",
    category: "ANALYSE",
    pricing_type: "DIRECT",
    direct_price: 40,
    coefficient: 1,
    letter: "B",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-GLYCEMIE",
    name: "Glycémie",
    description: "Dosage du sucre dans le sang",
    department: "LABORATOIRE",
    category: "ANALYSE",
    pricing_type: "DIRECT",
    direct_price: 30,
    coefficient: 2,
    letter: "B",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-NFS",
    name: "Numération formule sanguine (NFS)",
    description: "Analyse complète du sang",
    department: "LABORATOIRE",
    category: "ANALYSE",
    pricing_type: "DIRECT",
    direct_price: 110,
    coefficient: 100,
    letter: "B",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-TEST-GROSSESSE",
    name: "Test de grossesse",
    description: "Détection hormonale de grossesse",
    department: "LABORATOIRE",
    category: "ANALYSE",
    pricing_type: "DIRECT",
    direct_price: 80,
    coefficient: 5,
    letter: "B",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-ECHO-PELV",
    name: "Échographie pelvienne",
    description: "Exploration des organes pelviens",
    department: "GYNECOLOGIE",
    category: "IMAGING",
    pricing_type: "DIRECT",
    direct_price: 350,
    coefficient: 20,
    letter: "KE",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-MAMMOGRAPHIE",
    name: "Mammographie",
    description: "Imagerie des seins",
    department: "RADIOLOGIE",
    category: "IMAGING",
    pricing_type: "DIRECT",
    direct_price: 300,
    coefficient: 20,
    letter: "Z",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-KINE-SEANCE",
    name: "Séance de kinésithérapie",
    description: "Rééducation fonctionnelle",
    department: "KINESITHERAPIE",
    category: "REEDUCATION",
    pricing_type: "DIRECT",
    direct_price: 120,
    coefficient: 7,
    letter: "AMM",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-CONSULT-CARDIO",
    name: "Consultation en cardiologie",
    description: "Consultation spécialisée en cardiologie",
    department: "CARDIOLOGIE",
    category: "CONSULTATION",
    pricing_type: "DIRECT",
    direct_price: 250,
    coefficient: 1,
    letter: "Cs",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-CONSULT-DERMA",
    name: "Consultation dermatologique",
    description: "Consultation spécialisée en dermatologie",
    department: "DERMATOLOGIE",
    category: "CONSULTATION",
    pricing_type: "DIRECT",
    direct_price: 220,
    coefficient: 1,
    letter: "Cs",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-CONSULT-GYNECO",
    name: "Consultation gynécologique",
    description: "Consultation spécialisée en gynécologie",
    department: "GYNECOLOGIE",
    category: "CONSULTATION",
    pricing_type: "DIRECT",
    direct_price: 250,
    coefficient: 1,
    letter: "Cs",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-CONSULT-ORL",
    name: "Consultation ORL",
    description: "Consultation en oto-rhino-laryngologie",
    department: "ORL",
    category: "CONSULTATION",
    pricing_type: "DIRECT",
    direct_price: 230,
    coefficient: 1,
    letter: "Cs",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-CONSULT-OPHTALMO",
    name: "Consultation ophtalmologique",
    description: "Consultation en ophtalmologie",
    department: "OPHTALMOLOGIE",
    category: "CONSULTATION",
    pricing_type: "DIRECT",
    direct_price: 230,
    coefficient: 1,
    letter: "Cs",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-FOND-OEIL",
    name: "Examen du fond d’œil",
    description: "Analyse du fond de l’œil",
    department: "OPHTALMOLOGIE",
    category: "DIAGNOSTIC",
    pricing_type: "DIRECT",
    direct_price: 150,
    coefficient: 10,
    letter: "K",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-TONOMETRIE",
    name: "Tonométrie oculaire",
    description: "Mesure de la pression intraoculaire",
    department: "OPHTALMOLOGIE",
    category: "DIAGNOSTIC",
    pricing_type: "DIRECT",
    direct_price: 120,
    coefficient: 8,
    letter: "K",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-AUDIOMETRIE",
    name: "Audiométrie",
    description: "Test de l’audition",
    department: "ORL",
    category: "DIAGNOSTIC",
    pricing_type: "DIRECT",
    direct_price: 150,
    coefficient: 10,
    letter: "K",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-ENDOSCOPIE-NASALE",
    name: "Endoscopie nasale",
    description: "Exploration des fosses nasales",
    department: "ORL",
    category: "IMAGING",
    pricing_type: "DIRECT",
    direct_price: 200,
    coefficient: 15,
    letter: "K",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-ABLATION-KYSTE",
    name: "Ablation de kyste cutané",
    description: "Exérèse d’un kyste sous-cutané",
    department: "DERMATOLOGIE",
    category: "CHIRURGIE",
    pricing_type: "DIRECT",
    direct_price: 250,
    coefficient: 15,
    letter: "C",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-EXERSE-NAEVUS",
    name: "Exérèse de nævus",
    description: "Ablation d’un grain de beauté",
    department: "DERMATOLOGIE",
    category: "CHIRURGIE",
    pricing_type: "DIRECT",
    direct_price: 200,
    coefficient: 20,
    letter: "C",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-TRAITEMENT-VERRUE",
    name: "Traitement de verrue",
    description: "Destruction de verrues cutanées",
    department: "DERMATOLOGIE",
    category: "SOINS",
    pricing_type: "DIRECT",
    direct_price: 120,
    coefficient: 10,
    letter: "C",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-DRAINAGE-ABCES",
    name: "Drainage d'abcès cutané",
    description: "Incision et évacuation d’un abcès",
    department: "DERMATOLOGIE",
    category: "URGENCE",
    pricing_type: "DIRECT",
    direct_price: 200,
    coefficient: 20,
    letter: "C",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-INFILTRATION-ARTICULAIRE",
    name: "Infiltration articulaire",
    description: "Injection intra-articulaire thérapeutique",
    department: "RHEUMATOLOGIE",
    category: "SOINS",
    pricing_type: "DIRECT",
    direct_price: 180,
    coefficient: 10,
    letter: "K",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-RADIO-GENOU",
    name: "Radiographie du genou",
    description: "Imagerie radiologique du genou",
    department: "RADIOLOGIE",
    category: "IMAGING",
    pricing_type: "DIRECT",
    direct_price: 180,
    coefficient: 15,
    letter: "Z",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-RADIO-RACHIS",
    name: "Radiographie du rachis",
    description: "Radiographie de la colonne vertébrale",
    department: "RADIOLOGIE",
    category: "IMAGING",
    pricing_type: "DIRECT",
    direct_price: 200,
    coefficient: 18,
    letter: "Z",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-ECHO-CARDIAQUE",
    name: "Échographie cardiaque",
    description: "Exploration du cœur par ultrasons",
    department: "CARDIOLOGIE",
    category: "IMAGING",
    pricing_type: "DIRECT",
    direct_price: 400,
    coefficient: 25,
    letter: "KE",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-DOPPLER",
    name: "Écho-Doppler vasculaire",
    description: "Étude du flux sanguin",
    department: "CARDIOLOGIE",
    category: "IMAGING",
    pricing_type: "DIRECT",
    direct_price: 350,
    coefficient: 20,
    letter: "KE",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-SPIROMETRIE",
    name: "Spirométrie",
    description: "Test de la fonction respiratoire",
    department: "PNEUMOLOGIE",
    category: "DIAGNOSTIC",
    pricing_type: "DIRECT",
    direct_price: 180,
    coefficient: 10,
    letter: "K",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-NEBULISATION",
    name: "Nébulisation",
    description: "Administration de médicaments inhalés",
    department: "PNEUMOLOGIE",
    category: "SOINS",
    pricing_type: "DIRECT",
    direct_price: 100,
    coefficient: 5,
    letter: "K",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-SCANNER-CEREBRAL",
    name: "Scanner cérébral",
    description: "Tomodensitométrie du cerveau",
    department: "RADIOLOGIE",
    category: "IMAGING",
    pricing_type: "DIRECT",
    direct_price: 900,
    coefficient: 50,
    letter: "Z",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-SCANNER-THORACIQUE",
    name: "Scanner thoracique",
    description: "Scanner des poumons et du thorax",
    department: "RADIOLOGIE",
    category: "IMAGING",
    pricing_type: "DIRECT",
    direct_price: 950,
    coefficient: 55,
    letter: "Z",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-SCANNER-ABDOMINAL",
    name: "Scanner abdominal",
    description: "Scanner de l’abdomen",
    department: "RADIOLOGIE",
    category: "IMAGING",
    pricing_type: "DIRECT",
    direct_price: 950,
    coefficient: 55,
    letter: "Z",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-IRM-CEREBRALE",
    name: "IRM cérébrale",
    description: "Imagerie par résonance magnétique du cerveau",
    department: "RADIOLOGIE",
    category: "IMAGING",
    pricing_type: "DIRECT",
    direct_price: 1500,
    coefficient: 80,
    letter: "Z",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-IRM-GENOU",
    name: "IRM du genou",
    description: "IRM du genou",
    department: "RADIOLOGIE",
    category: "IMAGING",
    pricing_type: "DIRECT",
    direct_price: 1300,
    coefficient: 70,
    letter: "Z",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-IRM-RACHIS",
    name: "IRM du rachis",
    description: "IRM de la colonne vertébrale",
    department: "RADIOLOGIE",
    category: "IMAGING",
    pricing_type: "DIRECT",
    direct_price: 1400,
    coefficient: 75,
    letter: "Z",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },

  // GYNECO / OBSTETRIQUE
  {
    code: "NGAP-ECHO-GROSSESSE",
    name: "Échographie de grossesse",
    description: "Suivi échographique de grossesse",
    department: "GYNECOLOGIE",
    category: "OBSTETRIQUE",
    pricing_type: "DIRECT",
    direct_price: 300,
    coefficient: 20,
    letter: "KE",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-ECHO-MORPHO",
    name: "Échographie morphologique",
    description: "Échographie détaillée du fœtus",
    department: "GYNECOLOGIE",
    category: "OBSTETRIQUE",
    pricing_type: "DIRECT",
    direct_price: 450,
    coefficient: 30,
    letter: "KE",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-SUIVI-GROSSESSE",
    name: "Consultation de suivi de grossesse",
    description: "Suivi médical de grossesse",
    department: "GYNECOLOGIE",
    category: "CONSULTATION",
    pricing_type: "DIRECT",
    direct_price: 200,
    coefficient: 1,
    letter: "C",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-FROTTIS",
    name: "Frottis cervico-vaginal",
    description: "Dépistage du cancer du col",
    department: "GYNECOLOGIE",
    category: "PREVENTION",
    pricing_type: "DIRECT",
    direct_price: 150,
    coefficient: 10,
    letter: "C",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },

  // URGENCE / COURANT
  {
    code: "NGAP-REDUCTION-LUXATION",
    name: "Réduction de luxation",
    description: "Remise en place d’une articulation luxée",
    department: "URGENCE",
    category: "TRAUMATOLOGIE",
    pricing_type: "DIRECT",
    direct_price: 300,
    coefficient: 15,
    letter: "K",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-PLATRE",
    name: "Pose de plâtre",
    description: "Immobilisation d’un membre",
    department: "URGENCE",
    category: "TRAUMATOLOGIE",
    pricing_type: "DIRECT",
    direct_price: 250,
    coefficient: 10,
    letter: "K",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-CHANGEMENT-PLATRE",
    name: "Changement de plâtre",
    description: "Renouvellement d’un plâtre",
    department: "URGENCE",
    category: "TRAUMATOLOGIE",
    pricing_type: "DIRECT",
    direct_price: 150,
    coefficient: 5,
    letter: "K",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-SUTURE-PROFONDE",
    name: "Suture de plaie profonde",
    description: "Suture de plaie complexe",
    department: "URGENCE",
    category: "CHIRURGIE",
    pricing_type: "DIRECT",
    direct_price: 300,
    coefficient: 20,
    letter: "K",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },

  // CARDIO / RESPIRATOIRE
  {
    code: "NGAP-HOLTER",
    name: "Holter ECG 24h",
    description: "Enregistrement ECG sur 24h",
    department: "CARDIOLOGIE",
    category: "DIAGNOSTIC",
    pricing_type: "DIRECT",
    direct_price: 400,
    coefficient: 25,
    letter: "K",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-HOLTER-TA",
    name: "Holter tensionnel",
    description: "Mesure tension artérielle sur 24h",
    department: "CARDIOLOGIE",
    category: "DIAGNOSTIC",
    pricing_type: "DIRECT",
    direct_price: 350,
    coefficient: 20,
    letter: "K",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },

  // DIGESTIF
  {
    code: "NGAP-ENDOSCOPIE",
    name: "Endoscopie digestive",
    description: "Exploration de l’estomac",
    department: "GASTROENTEROLOGIE",
    category: "IMAGING",
    pricing_type: "DIRECT",
    direct_price: 600,
    coefficient: 40,
    letter: "K",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-COLONOSCOPIE",
    name: "Coloscopie",
    description: "Exploration du côlon",
    department: "GASTROENTEROLOGIE",
    category: "IMAGING",
    pricing_type: "DIRECT",
    direct_price: 900,
    coefficient: 60,
    letter: "K",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },

  // UROLOGIE
  {
    code: "NGAP-ECHO-RENALE",
    name: "Échographie rénale",
    description: "Exploration des reins",
    department: "UROLOGIE",
    category: "IMAGING",
    pricing_type: "DIRECT",
    direct_price: 300,
    coefficient: 20,
    letter: "KE",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-SONDAGE-VESICAL",
    name: "Sondage vésical",
    description: "Pose de sonde urinaire",
    department: "UROLOGIE",
    category: "SOINS",
    pricing_type: "DIRECT",
    direct_price: 120,
    coefficient: 5,
    letter: "K",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  }
    ,
  // =========================
  // NEPHROLOGIE
  // =========================
  {
    code: "NGAP-CONSULT-NEPHRO",
    name: "Consultation en néphrologie",
    description: "Consultation spécialisée des maladies rénales",
    department: "NEPHROLOGIE",
    category: "CONSULTATION",
    pricing_type: "DIRECT",
    direct_price: 250,
    coefficient: 1,
    letter: "Cs",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-ECHO-RENAL",
    name: "Échographie rénale",
    description: "Exploration des reins par ultrasons",
    department: "NEPHROLOGIE",
    category: "IMAGING",
    pricing_type: "DIRECT",
    direct_price: 300,
    coefficient: 20,
    letter: "KE",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
  code: "NGAP-DIALYSE",
  name: "Séance d’hémodialyse",
  description: "Traitement de suppléance rénale par hémodialyse",
  department: "NEPHROLOGIE",
  category: "TRAITEMENT",
  pricing_type: "DIRECT",
  direct_price: 800,
  coefficient: 50,
  letter: "K",
  is_active: true,
  is_bookable: true,
  source: "NGAP"
},

  // =========================
  // PEDIATRIE
  // =========================
  {
    code: "NGAP-CONSULT-PEDIATRIE",
    name: "Consultation pédiatrique",
    description: "Consultation médicale pour enfant",
    department: "PEDIATRIE",
    category: "CONSULTATION",
    pricing_type: "DIRECT",
    direct_price: 200,
    coefficient: 1,
    letter: "C",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-SUIVI-NOURRISSON",
    name: "Suivi du nourrisson",
    description: "Consultation de suivi du bébé",
    department: "PEDIATRIE",
    category: "SUIVI",
    pricing_type: "DIRECT",
    direct_price: 180,
    coefficient: 1,
    letter: "C",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-VACCINATION",
    name: "Vaccination",
    description: "Administration de vaccin",
    department: "PEDIATRIE",
    category: "PREVENTION",
    pricing_type: "DIRECT",
    direct_price: 100,
    coefficient: 5,
    letter: "C",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },

  // =========================
  // PSYCHIATRIE
  // =========================
  {
    code: "NGAP-CONSULT-PSY",
    name: "Consultation psychiatrique",
    description: "Consultation avec un psychiatre",
    department: "PSYCHIATRIE",
    category: "CONSULTATION",
    pricing_type: "DIRECT",
    direct_price: 300,
    coefficient: 1,
    letter: "CNPSY",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-SUIVI-PSY",
    name: "Suivi psychiatrique",
    description: "Consultation de suivi en psychiatrie",
    department: "PSYCHIATRIE",
    category: "SUIVI",
    pricing_type: "DIRECT",
    direct_price: 250,
    coefficient: 1,
    letter: "CNPSY",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },

  // =========================
  // ONCOLOGIE
  // =========================
  {
    code: "NGAP-CONSULT-ONCO",
    name: "Consultation en oncologie",
    description: "Consultation spécialisée en cancérologie",
    department: "ONCOLOGIE",
    category: "CONSULTATION",
    pricing_type: "DIRECT",
    direct_price: 300,
    coefficient: 1,
    letter: "Cs",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-SUIVI-ONCO",
    name: "Suivi oncologique",
    description: "Consultation de suivi pour patient cancéreux",
    department: "ONCOLOGIE",
    category: "SUIVI",
    pricing_type: "DIRECT",
    direct_price: 280,
    coefficient: 1,
    letter: "Cs",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },

  // =========================
  // DENTISTERIE
  // =========================
  {
    code: "NGAP-CONSULT-DENTAIRE",
    name: "Consultation dentaire",
    description: "Consultation chez le dentiste",
    department: "DENTISTERIE",
    category: "CONSULTATION",
    pricing_type: "DIRECT",
    direct_price: 150,
    coefficient: 1,
    letter: "C",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-DETARTRAGE",
    name: "Détartrage",
    description: "Nettoyage des dents",
    department: "DENTISTERIE",
    category: "SOINS",
    pricing_type: "DIRECT",
    direct_price: 200,
    coefficient: 10,
    letter: "D",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-SOIN-CARIE",
    name: "Soin de carie",
    description: "Traitement d’une carie dentaire",
    department: "DENTISTERIE",
    category: "SOINS",
    pricing_type: "DIRECT",
    direct_price: 250,
    coefficient: 15,
    letter: "D",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },

  // =========================
  // ORTHOPEDIE
  // =========================
  {
    code: "NGAP-CONSULT-ORTHO",
    name: "Consultation en orthopédie",
    description: "Consultation spécialisée en traumatologie",
    department: "ORTHOPEDIE",
    category: "CONSULTATION",
    pricing_type: "DIRECT",
    direct_price: 250,
    coefficient: 1,
    letter: "Cs",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-INFILTRATION-ORTHO",
    name: "Infiltration orthopédique",
    description: "Injection thérapeutique articulaire",
    department: "ORTHOPEDIE",
    category: "SOINS",
    pricing_type: "DIRECT",
    direct_price: 180,
    coefficient: 10,
    letter: "K",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  },
  {
    code: "NGAP-REDUC-FRACTURE",
    name: "Réduction de fracture simple",
    description: "Traitement orthopédique d’une fracture",
    department: "ORTHOPEDIE",
    category: "TRAUMATOLOGIE",
    pricing_type: "DIRECT",
    direct_price: 300,
    coefficient: 25,
    letter: "A",
    is_active: true,
    is_bookable: true,
    source: "NGAP"
  }

]
module.exports = { PATIENT_BOOKABLE_SERVICES }