apiVersion: v1
kind: Service
metadata:
  name: consultation-records-service
spec:
  selector:
    app: consultation-records-service
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005
  type: NodePort

