apiVersion: apps/v1
kind: Deployment
metadata:
  name: consultation-records-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consultation-records-service
  template:
    metadata:
      labels:
        app: consultation-records-service
    spec:
      containers:
        - name: consultation-records-service
          image: myheart-consultation-records-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5005
          envFrom:
            - configMapRef:
                name: consultation-config
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: consultation-secret
                  key: JWT_SECRET          readinessProbe:
            tcpSocket:
              port: 5005
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 5005
            initialDelaySeconds: 15
            periodSeconds: 10
