apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-service
  template:
    metadata:
      labels:
        app: doctor-service
    spec:
      containers:
        - name: doctor-service
          image: myheart-doctor-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5003
          envFrom:
            - configMapRef:
                name: doctor-config
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: doctor-secret
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /doctors
              port: 5003
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /doctors
              port: 5003
            initialDelaySeconds: 15
            periodSeconds: 10

