apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
        - name: patient-service
          image: myheart-patient-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5002
          envFrom:
            - configMapRef:
                name: patient-config
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: patient-secret
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /patients/test
              port: 5002
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /patients/test
              port: 5002
            initialDelaySeconds: 15
            periodSeconds: 10

