global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:5000"]

  - job_name: "appointment-service"
    static_configs:
      - targets: ["appointment-service:5004"]
  
  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:5001"]